const PROMPTS_LOADING = 'PROMPTS_LOADING';
const PROMPTS_FAILED = 'PROMPTS_FAILED';
const ADD_PROMPTS = 'ADD_PROMPTS';

const PARENTALCONTROLS_LOADING = 'PARENTALCONTROLS_LOADING';
const PARENTALCONTROLS_FAILED = 'PARENTALCONTROLS_FAILED';
const ADD_PARENTALCONTROLS = 'ADD_PARENTALCONTROLS';

const GALLERY_LOADING = 'GALLERY_LOADING';
const GALLERY_FAILED = 'GALLERY_FAILED';
const ADD_GALLERY = 'ADD_GALLERY';

const USER_LOADING = 'USER_LOADING';
const USER_FAILED = 'USER_FAILED';
const ADD_USER = 'ADD_USER';